### ISSUE TITLE
I can't get on piskel!

### ISSUE THREAD

**Issue by Mruble** [juliandescottes/piskel-website#12]

**Comment by juliandescottes** [comment]
Hi! 

Can you give more details about your issue:
- which URL are you using ?
- which browser are you using ?
- do you see any error message ?

Thanks!

**Comment by Mruble** [comment]
It says Sorry!
Unexpected error
Oops. Something bad happened on our side.
If you can reproduce this error then file this issue on github.

**Comment by Mruble** [comment]
Also I am user 5220958856019968 or Matthew Ruble so if you can do anything that wound be great.

**Comment by juliandescottes** [comment]
Ah thanks for the additional info, definitely helps! 

For information I think you are currently the user who has the most sprites saved in their gallery.

I just looked at the logs and it looks like you have so many sprites now that displaying your user page simply makes the server crash.

So first of all, don't worry, your sprites are not lost or anything. 
I'll work on that later today and hopefully I can either find a workaround or implement a proper fix. 

I'll update the issue as soon as I have anything.

**Comment by Mruble** [comment]
I am going to delete some pixel art just in case so it doesn't crash the servers again.

**Comment by juliandescottes** [comment]
I'm not sure how you can do that if you can't access your account page? 

In any case, I wouldn't do it if I were you. I will do my best to have a fix ready sometime later today (even if it's an ugly workaround).

**Comment by Mruble** [comment]
okay

**Comment by juliandescottes** [comment]
I'm almost there. I have a fix that seems to work fine on my beta server (http://beta.piskel-app.appspot.com/user/5220958856019968) 

I can't really check if all your sprites are correctly displayed since none of them are public. But I believe they should be there. At least the stats compute fine.

Feedback appreciated.

**Comment by Mruble** [comment]
I will go to create a sprite and put it to public to see if that will help.

**Comment by juliandescottes** [comment]
Thank you, that's great!
 I can see your public sprite so I guess this means it works for you when you are logged in too.

I'll need some time to review & polish the fix, so I don't expect to update the real website before tomorrow. In the meantime you can use the beta URL if you want!

**Comment by juliandescottes** [comment]
Should now be fixed on piskelapp.com ! Let me know if you face any issue.

**Comment by Mruble** [comment]
I have one more issue I cant zoom in it just turns grey.
